<template>
  <div class="divBox">
    <el-alert title="盘点先固化账面快照。审核时如快照后的库存已经发生正常业务变化，系统会拒绝用过期盘点覆盖真实库存；盘盈盘亏均通过统一库存流水调整。" type="warning" :closable="false" />
    <el-card shadow="never" class="mt14">
      <el-form :inline="true" size="mini"><el-form-item label="状态"><el-select v-model="query.status" clearable><el-option v-for="x in statuses" :key="x.value" :label="x.label" :value="x.value"/></el-select></el-form-item><el-form-item><el-button type="primary" @click="load">查询</el-button><el-button type="success" @click="openCreate">创建盘点</el-button></el-form-item></el-form>
      <el-table v-loading="loading" :data="data.list" size="mini" border>
        <el-table-column prop="checkNo" label="盘点单号" min-width="170"/><el-table-column prop="ownerName" label="库存主体" min-width="150"/><el-table-column label="盘点类型" width="90"><template slot-scope="{row}">{{row.checkType==='FULL'?'全盘':'抽盘'}}</template></el-table-column><el-table-column label="差异数量" width="90"><template slot-scope="{row}"><span :class="{danger:Number(row.differenceQuantity)!==0}">{{row.differenceQuantity||0}}</span></template></el-table-column><el-table-column label="差异金额" width="110"><template slot-scope="{row}">¥{{money(row.differenceAmount)}}</template></el-table-column><el-table-column label="状态" width="100"><template slot-scope="{row}"><el-tag size="mini" :type="tag(row.status)">{{statusText(row.status)}}</el-tag></template></el-table-column><el-table-column prop="snapshotTime" label="快照时间" min-width="155"/><el-table-column label="操作" width="190" fixed="right"><template slot-scope="{row}"><el-button type="text" @click="view(row)">{{row.status==='COUNTING'?'录入盘点':'详情'}}</el-button><el-button v-if="row.status==='SUBMITTED'" type="text" style="color:#67c23a" @click="audit(row,true)">通过</el-button><el-button v-if="row.status==='SUBMITTED'" type="text" style="color:#f56c6c" @click="audit(row,false)">驳回</el-button></template></el-table-column>
      </el-table>
      <el-pagination background layout="total,prev,pager,next" :total="Number(data.total||0)" :current-page="query.page" :page-size="query.limit" @current-change="p=>{query.page=p;load()}"/>
    </el-card>

    <el-dialog title="创建盘点" :visible.sync="createVisible" width="520px">
      <el-form label-width="100px"><el-form-item label="库存主体"><el-select v-model="createForm.stockAccountId" filterable style="width:100%" placeholder="请选择真实库存主体"><el-option v-for="x in accounts" :key="x.id" :label="accountLabel(x)" :value="x.id"/></el-select></el-form-item><el-form-item label="盘点类型"><el-select v-model="createForm.checkType" style="width:100%"><el-option label="全盘" value="FULL"/><el-option label="抽盘" value="PARTIAL"/></el-select></el-form-item><el-form-item label="说明"><el-input v-model.trim="createForm.remark" type="textarea"/></el-form-item></el-form>
      <span slot="footer"><el-button @click="createVisible=false">取消</el-button><el-button type="primary" :loading="saving" @click="create">创建账面快照</el-button></span>
    </el-dialog>

    <el-drawer title="盘点详情" :visible.sync="detailVisible" size="78%">
      <div v-if="detail" class="drawer-body">
        <el-descriptions :column="4" border size="small"><el-descriptions-item label="盘点单号">{{detail.checkNo}}</el-descriptions-item><el-descriptions-item label="库存主体">{{detail.ownerName||detail.ownerUserId}}</el-descriptions-item><el-descriptions-item label="状态"><el-tag size="mini" :type="tag(detail.status)">{{statusText(detail.status)}}</el-tag></el-descriptions-item><el-descriptions-item label="快照时间">{{detail.snapshotTime}}</el-descriptions-item><el-descriptions-item label="差异数量">{{detail.differenceQuantity||0}}</el-descriptions-item><el-descriptions-item label="差异金额">¥{{money(detail.differenceAmount)}}</el-descriptions-item><el-descriptions-item label="审核说明" :span="2">{{detail.auditRemark||'--'}}</el-descriptions-item></el-descriptions>
        <el-table :data="detail.items||[]" size="mini" border class="mt14">
          <el-table-column prop="productName" label="商品" min-width="160"/><el-table-column label="规格" min-width="140"><template slot-scope="{row}"><div>{{row.skuName||'默认规格'}}</div><small>{{row.skuCode||'--'}}</small></template></el-table-column><el-table-column prop="bookQuantity" label="账面" width="75"/><el-table-column label="实盘" width="170"><template slot-scope="{row}"><div v-if="detail.status==='COUNTING'" class="count-cell"><el-input-number v-model="row.actualQuantity" :min="0" size="mini" controls-position="right"/><el-button type="text" :loading="savingItemId===row.id" @click="saveItem(row)">保存</el-button></div><span v-else>{{row.actualQuantity==null?'--':row.actualQuantity}}</span></template></el-table-column><el-table-column label="差异" width="80"><template slot-scope="{row}"><span :class="{danger:Number(row.differenceQuantity)!==0}">{{row.actualQuantity==null?'--':Number(row.actualQuantity)-Number(row.bookQuantity||0)}}</span></template></el-table-column><el-table-column label="差异金额" width="110"><template slot-scope="{row}">¥{{money(row.differenceAmount)}}</template></el-table-column><el-table-column prop="adjustStatus" label="调整状态" width="100"/><el-table-column prop="countRemark" label="盘点说明" min-width="140"/></el-table>
        <div v-if="detail.status==='COUNTING'" class="drawer-actions"><el-button @click="reloadDetail">刷新</el-button><el-button type="primary" :loading="submitting" @click="submit">提交审核</el-button></div>
        <div v-if="detail.status==='SUBMITTED'" class="drawer-actions"><el-button type="danger" @click="audit(detail,false)">驳回</el-button><el-button type="success" @click="audit(detail,true)">审核通过并应用差异</el-button></div>
        <template v-if="detail.logs&&detail.logs.length"><h4>处理日志</h4><el-timeline><el-timeline-item v-for="x in detail.logs" :key="x.id" :timestamp="x.createTime"><strong>{{x.action}}</strong>　{{x.beforeStatus||'--'}} → {{x.afterStatus||'--'}}<div class="log-remark">{{x.remark||'--'}}</div></el-timeline-item></el-timeline></template>
      </div>
    </el-drawer>
  </div>
</template>
<script>
import { getJkStockAccountList } from '@/api/jkBusiness'
import { getStockCheckList, getStockCheckDetail, createStockCheck, saveStockCheckCount, submitStockCheck, auditStockCheck } from '@/api/jkPhase3'
export default{
  data(){return{loading:false,saving:false,submitting:false,savingItemId:null,data:{list:[],total:0},query:{page:1,limit:20,status:''},statuses:[{label:'盘点中',value:'COUNTING'},{label:'待审核',value:'SUBMITTED'},{label:'已通过',value:'APPROVED'},{label:'已驳回',value:'REJECTED'}],createVisible:false,detailVisible:false,detail:null,accounts:[],createForm:{stockAccountId:null,checkType:'FULL',remark:''}}},
  created(){this.load();this.loadAccounts()},
  methods:{
    load(){this.loading=true;getStockCheckList(this.query).then(r=>{const d=r.data||r||{};this.data={list:d.list||d.records||[],total:d.total||0}}).finally(()=>this.loading=false)},
    loadAccounts(){getJkStockAccountList({page:1,limit:200,status:true}).then(r=>{const d=r.data||r||{};this.accounts=d.list||d.records||[]})},
    openCreate(){this.createForm={stockAccountId:null,checkType:'FULL',remark:''};this.createVisible=true},
    create(){if(!this.createForm.stockAccountId)return this.$message.warning('请选择库存主体');this.saving=true;createStockCheck({...this.createForm,requestNo:'CHECK-'+Date.now()}).then(r=>{this.$message.success('盘点快照已创建');this.createVisible=false;this.load();this.view(r.data||r)}).finally(()=>this.saving=false)},
    view(row){getStockCheckDetail(row.id).then(r=>{this.detail=r.data||r;this.detailVisible=true})},reloadDetail(){if(this.detail)this.view(this.detail)},
    saveItem(row){if(row.actualQuantity==null||Number(row.actualQuantity)<0)return this.$message.warning('实盘数量不能小于0');this.savingItemId=row.id;saveStockCheckCount(this.detail.id,{itemId:row.id,actualQuantity:Number(row.actualQuantity),remark:row.countRemark||'后台盘点录入'}).then(()=>{this.$message.success('实盘数量已保存');this.reloadDetail()}).finally(()=>this.savingItemId=null)},
    submit(){if((this.detail.items||[]).some(x=>x.actualQuantity==null))return this.$message.warning('请先录入并保存全部商品的实盘数量');this.$prompt('请输入提交说明','提交盘点审核',{inputValue:'盘点录入完成，提交审核',inputValidator:v=>!!String(v||'').trim()||'说明不能为空'}).then(({value})=>{this.submitting=true;return submitStockCheck(this.detail.id,{requestNo:'SUBMIT-'+this.detail.id+'-'+Date.now(),remark:value})}).then(()=>{this.$message.success('已提交审核');this.reloadDetail();this.load()}).catch(()=>{}).finally(()=>this.submitting=false)},
    audit(row,approved){const title=approved?'审核通过并应用盘点差异':'驳回盘点';const placeholder=approved?'请输入审核依据':'请输入驳回原因';this.$prompt(placeholder,title,{inputValidator:v=>!!String(v||'').trim()||'审核说明不能为空'}).then(({value})=>auditStockCheck({checkId:row.id,approved,requestNo:(approved?'APPROVE-':'REJECT-')+row.id+'-'+Date.now(),remark:value})).then(()=>{this.$message.success(approved?'盘点差异已通过统一库存流水应用':'盘点已驳回');if(this.detailVisible&&this.detail&&this.detail.id===row.id)this.reloadDetail();this.load()}).catch(()=>{})},
    accountLabel(x){return[x.accountNo,x.ownerName||x.roleName||x.accountTypeText].filter(Boolean).join(' / ')},money(v){return Number(v||0).toFixed(2)},statusText(v){return{COUNTING:'盘点中',SUBMITTED:'待审核',APPROVED:'已通过',REJECTED:'已驳回',CANCELLED:'已取消'}[v]||v},tag(v){return v==='APPROVED'?'success':v==='REJECTED'?'danger':v==='SUBMITTED'?'warning':'info'}
  }
}
</script>
<style scoped>.mt14{margin-top:14px}.drawer-body{padding:0 24px 30px}.danger{color:#f56c6c;font-weight:600}.el-pagination{margin-top:18px;text-align:right}.count-cell{display:flex;align-items:center;gap:8px}.count-cell .el-input-number{width:110px}.drawer-actions{margin-top:18px;text-align:right}.log-remark{margin-top:5px;color:#909399}small{color:#909399}</style>
