<template>
  <div class="divBox">
    <el-card shadow="never">
      <div slot="header"><span>V3.1 运营中心</span></div>
      <el-alert :closable="false" type="warning" show-icon title="微信小程序码、订阅消息和 MinIO 默认关闭。参数未配置时接口会明确失败，不生成占位码、假消息或数据库文件。" />
      <el-tabs v-model="tab" style="margin-top:14px" @tab-click="load">
        <el-tab-pane label="推广效果" name="promotion" />
        <el-tab-pane label="订阅消息" name="message" />
        <el-tab-pane label="报表导出" name="export" />
        <el-tab-pane label="健康报告核查" name="health" />
      </el-tabs>

      <template v-if="tab==='promotion'">
        <el-form inline size="small"><el-form-item label="场景ID"><el-input-number v-model="promotionQuery.sceneId" :min="1" /></el-form-item><el-form-item label="日期"><el-date-picker v-model="promotionDates" type="daterange" value-format="yyyy-MM-dd" /></el-form-item><el-button @click="loadPromotion">查询</el-button></el-form>
        <el-table v-loading="loading" :data="list" border size="mini"><el-table-column prop="sceneId" label="场景ID"/><el-table-column prop="statDate" label="日期"/><el-table-column prop="scanCount" label="扫码"/><el-table-column prop="newUserCount" label="新增用户"/><el-table-column prop="initialBindCount" label="首次绑定"/><el-table-column prop="effectiveBindCount" label="有效绑定"/><el-table-column prop="buyerCount" label="购买用户"/><el-table-column prop="saleAmount" label="成交金额"/></el-table>
      </template>

      <template v-else-if="tab==='message'">
        <el-form inline size="small"><el-form-item label="事件类型"><el-input v-model="messageQuery.eventType" clearable /></el-form-item><el-form-item label="状态"><el-select v-model="messageQuery.status" clearable><el-option v-for="x in messageStatuses" :key="x" :label="x" :value="x"/></el-select></el-form-item><el-form-item label="接收用户"><el-input-number v-model="messageQuery.receiverUserId" :min="1" /></el-form-item><el-button @click="loadMessage">查询</el-button><el-button type="primary" @click="runMessages">执行待发送</el-button></el-form>
        <el-table v-loading="loading" :data="list" border size="mini"><el-table-column prop="taskNo" label="任务编号" min-width="170"/><el-table-column prop="eventType" label="事件"/><el-table-column prop="receiverUserId" label="接收用户"/><el-table-column prop="templateCode" label="模板编码"/><el-table-column prop="status" label="状态"/><el-table-column prop="retryCount" label="重试"/><el-table-column prop="lastError" label="最近错误" min-width="220"/><el-table-column label="操作"><template slot-scope="s"><el-button v-if="['FAILED','RETRY','SKIPPED_DISABLED'].includes(s.row.status)" type="text" @click="retryMessage(s.row)">重试</el-button></template></el-table-column></el-table>
      </template>

      <template v-else-if="tab==='export'">
        <el-form inline size="small"><el-form-item label="报表类型"><el-select v-model="exportQuery.reportType" clearable><el-option v-for="x in reportTypes" :key="x.value" :label="x.label" :value="x.value" /></el-select></el-form-item><el-form-item label="状态"><el-select v-model="exportQuery.status" clearable><el-option v-for="x in exportStatuses" :key="x" :label="x" :value="x"/></el-select></el-form-item><el-button @click="loadExport">查询</el-button><el-button type="primary" @click="createExport">创建导出</el-button><el-button @click="runExports">执行待处理</el-button></el-form>
        <el-table v-loading="loading" :data="list" border size="mini"><el-table-column prop="taskNo" label="任务编号" min-width="170"/><el-table-column prop="reportType" label="报表类型"/><el-table-column prop="status" label="状态"/><el-table-column prop="progress" label="进度"/><el-table-column prop="fileName" label="文件" min-width="180"/><el-table-column prop="fileSize" label="大小"/><el-table-column prop="downloadCount" label="下载次数"/><el-table-column prop="errorMessage" label="错误" min-width="220"/><el-table-column label="操作" width="130"><template slot-scope="s"><el-button v-if="s.row.status==='COMPLETED'" type="text" @click="download(s.row)">获取链接</el-button><el-button v-if="s.row.status==='FAILED'" type="text" @click="retryExport(s.row)">重试</el-button></template></el-table-column></el-table>
      </template>

      <template v-else>
        <el-form inline size="small"><el-form-item label="用户ID" required><el-input-number v-model="healthQuery.userId" :min="1" /></el-form-item><el-form-item label="周期"><el-select v-model="healthQuery.period"><el-option label="近7天" value="WEEK"/><el-option label="近30天" value="MONTH"/></el-select></el-form-item><el-button type="primary" @click="loadHealth">生成核查</el-button></el-form>
        <el-descriptions v-if="healthReport.recordCount!==undefined" :column="3" border><el-descriptions-item label="周期">{{healthReport.startDate}} 至 {{healthReport.endDate}}</el-descriptions-item><el-descriptions-item label="记录次数">{{healthReport.recordCount}}</el-descriptions-item><el-descriptions-item label="风险">{{healthReport.riskLevelText}}</el-descriptions-item><el-descriptions-item label="平均值">{{healthReport.averageValue||'--'}}</el-descriptions-item><el-descriptions-item label="最高值">{{healthReport.maxValue||'--'}}</el-descriptions-item><el-descriptions-item label="最低值">{{healthReport.minValue||'--'}}</el-descriptions-item></el-descriptions>
        <el-alert v-if="healthReport.summaryText" :closable="false" type="info" :title="healthReport.summaryText" style="margin-top:14px" />
        <el-table v-if="healthReport.periodStats" :data="healthReport.periodStats" size="mini" border style="margin-top:14px"><el-table-column prop="periodText" label="时段"/><el-table-column prop="recordCount" label="次数"/><el-table-column prop="averageValue" label="平均值"/></el-table>
      </template>
    </el-card>
  </div>
</template>
<script>
import { getPromotionStats,getSubscriptionTasks,runSubscriptionTasks,retrySubscriptionTask,createReportExportTask,getReportExportTasks,runReportExportTasks,retryReportExportTask,downloadReportExportTask,getHealthReport } from '@/api/jkV31'
export default {data(){return{tab:'promotion',loading:false,list:[],promotionQuery:{page:1,limit:50,sceneId:null},promotionDates:[],messageQuery:{page:1,limit:50,eventType:'',status:'',receiverUserId:null},exportQuery:{page:1,limit:50,reportType:'',status:''},healthQuery:{userId:null,period:'WEEK'},healthReport:{},messageStatuses:['PENDING','RETRY','SUCCESS','FAILED','SKIPPED_DISABLED'],exportStatuses:['PENDING','RUNNING','COMPLETED','FAILED'],reportTypes:[{label:'业绩账本',value:'PERFORMANCE'},{label:'经营收益',value:'OPERATION_PROFIT'},{label:'线下销售',value:'OFFLINE_SALE'},{label:'库存盘点',value:'STOCK_CHECK'}]}},created(){this.load()},methods:{rows(r){const d=(r&&r.data)||r||{};return d.list||d.records||(Array.isArray(d)?d:[])},load(){if(this.tab==='promotion')this.loadPromotion();else if(this.tab==='message')this.loadMessage();else if(this.tab==='export')this.loadExport()},loadPromotion(){this.loading=true;const p=Object.assign({},this.promotionQuery);if(this.promotionDates&&this.promotionDates.length){p.startDate=this.promotionDates[0];p.endDate=this.promotionDates[1]}getPromotionStats(p).then(r=>this.list=this.rows(r)).finally(()=>this.loading=false)},loadMessage(){this.loading=true;getSubscriptionTasks(this.messageQuery).then(r=>this.list=this.rows(r)).finally(()=>this.loading=false)},runMessages(){runSubscriptionTasks({limit:20}).then(r=>{this.$message.success('处理完成：'+(((r&&r.data)!==undefined?r.data:r)||0));this.loadMessage()})},retryMessage(row){retrySubscriptionTask(row.id).then(()=>{this.$message.success('已重新进入队列');this.loadMessage()})},loadExport(){this.loading=true;getReportExportTasks(this.exportQuery).then(r=>this.list=this.rows(r)).finally(()=>this.loading=false)},createExport(){if(!this.exportQuery.reportType)return this.$message.warning('请选择报表类型');createReportExportTask({reportType:this.exportQuery.reportType,requestNo:'EXPORT-'+Date.now(),requestJson:'{}'}).then(()=>{this.$message.success('导出任务已创建');this.loadExport()})},runExports(){runReportExportTasks({limit:10}).then(r=>{this.$message.success('完成任务：'+(((r&&r.data)!==undefined?r.data:r)||0));this.loadExport()})},retryExport(row){retryReportExportTask(row.id).then(()=>{this.$message.success('重试完成');this.loadExport()})},download(row){downloadReportExportTask(row.id).then(r=>{const d=(r&&r.data)||r||{};if(!d.downloadUrl)return this.$message.warning('未获得下载链接，请检查 MinIO 配置');window.open(d.downloadUrl,'_blank')})},loadHealth(){if(!this.healthQuery.userId)return this.$message.warning('请输入用户ID');getHealthReport(this.healthQuery).then(r=>{this.healthReport=(r&&r.data)||r||{}})}}}
</script>
