<template>
  <div class="divBox">
    <el-alert :title="readyText" :type="status.ready?'success':'warning'" :closable="false" />
    <el-card shadow="never" class="mt14">
      <div slot="header" class="head"><span>推广码场景</span><el-button size="mini" type="primary" @click="edit()">新增场景版本</el-button></div>
      <el-form :inline="true" size="mini"><el-form-item label="关键词"><el-input v-model="query.keyword" clearable /></el-form-item><el-form-item label="状态"><el-select v-model="query.status" clearable><el-option label="启用" :value="true"/><el-option label="关闭" :value="false"/></el-select></el-form-item><el-form-item><el-button type="primary" @click="load">查询</el-button><el-button @click="loadStatus">刷新配置状态</el-button></el-form-item></el-form>
      <el-table v-loading="loading" :data="data.list" size="mini">
        <el-table-column prop="sceneCode" label="场景编码" min-width="150"/><el-table-column prop="sceneName" label="场景名称" min-width="150"/><el-table-column prop="pagePath" label="小程序页面" min-width="210"/><el-table-column prop="roleCodes" label="适用角色" min-width="180"/><el-table-column prop="sceneTemplate" label="scene模板" min-width="160"/><el-table-column prop="versionNo" label="版本" width="70"/><el-table-column label="状态" width="90"><template slot-scope="{row}"><el-tag size="mini" :type="row.status?'success':'info'">{{row.status?'启用':'关闭'}}</el-tag></template></el-table-column><el-table-column label="操作" width="80"><template slot-scope="{row}"><el-button type="text" @click="edit(row)">编辑</el-button></template></el-table-column>
      </el-table>
      <el-pagination background layout="total,prev,pager,next" :total="Number(data.total||0)" :current-page="query.page" :page-size="query.limit" @current-change="p=>{query.page=p;load()}"/>
    </el-card>
    <el-dialog title="推广场景配置" :visible.sync="visible" width="620px">
      <el-form label-width="110px"><el-form-item label="场景编码"><el-input v-model.trim="form.sceneCode" :disabled="!!form.id" /></el-form-item><el-form-item label="场景名称"><el-input v-model.trim="form.sceneName" /></el-form-item><el-form-item label="小程序页面"><el-input v-model.trim="form.pagePath" placeholder="如 pages/index/index" /></el-form-item><el-form-item label="适用角色"><el-checkbox-group v-model="roles"><el-checkbox label="maker">创客</el-checkbox><el-checkbox label="partner">合伙人</el-checkbox><el-checkbox label="county_agent">区县代理</el-checkbox></el-checkbox-group></el-form-item><el-form-item label="scene模板"><el-input v-model.trim="form.sceneTemplate" placeholder="bind:{userId}，生成后不得超过微信32字节" /></el-form-item><el-form-item label="版本"><el-input-number v-model="form.versionNo" :min="1" /></el-form-item><el-form-item label="启用"><el-switch v-model="form.status"/><div class="tip">微信总开关、appid/secret和私有文件存储全部就绪后才允许启用。</div></el-form-item><el-form-item label="备注"><el-input v-model="form.remark" type="textarea" /></el-form-item></el-form>
      <span slot="footer"><el-button @click="visible=false">取消</el-button><el-button type="primary" :loading="saving" @click="save">保存</el-button></span>
    </el-dialog>
  </div>
</template>
<script>
import { getPromotionSceneList, savePromotionScene, getPromotionStatus } from '@/api/jkPhase3'
export default{data(){return{loading:false,saving:false,status:{},data:{list:[],total:0},query:{page:1,limit:20,keyword:'',status:null},visible:false,roles:[],form:{}}},computed:{readyText(){if(this.status.ready)return'微信与统一文件存储已就绪，可人工启用推广场景';return'推广码能力当前不可用：不会生成占位二维码，请检查微信总开关、appid/secret、私有存储和场景状态'}},created(){this.load();this.loadStatus()},methods:{load(){this.loading=true;getPromotionSceneList(this.query).then(r=>{const d=r.data||r||{};this.data={list:d.list||d.records||[],total:d.total||0}}).finally(()=>this.loading=false)},loadStatus(){getPromotionStatus().then(r=>this.status=r.data||r||{}).catch(()=>this.status={ready:false})},edit(row){this.form=row?{...row}:{sceneCode:'',sceneName:'',pagePath:'pages/index/index',sceneTemplate:'bind:{userId}',versionNo:1,status:false,remark:''};this.roles=String(this.form.roleCodes||'').split(',').filter(Boolean);this.visible=true},save(){if(!this.form.sceneCode||!this.form.sceneName||!this.form.pagePath||!this.form.sceneTemplate)return this.$message.warning('请填写完整场景信息');if(this.form.status&&!this.status.ready)return this.$message.warning('配置尚未就绪，不能启用场景');this.saving=true;savePromotionScene({...this.form,roleCodes:this.roles.join(',')}).then(()=>{this.$message.success('保存成功');this.visible=false;this.load();this.loadStatus()}).finally(()=>this.saving=false)}}}
</script>
<style scoped>.mt14{margin-top:14px}.head{display:flex;align-items:center;justify-content:space-between}.tip{margin-top:7px;color:#e6a23c;font-size:12px}.el-pagination{margin-top:18px;text-align:right}</style>
