import Layout from '@/layout';

const jkBusinessRouter = {
  path: '/operation/jzk',
  component: Layout,
  redirect: '/operation/jzk/platformOrder',
  name: 'JkBusiness',
  meta: {
    title: '九州康业务',
    icon: 'clipboard',
  },
  children: [
    { path: 'healthProvider', component: () => import('@/views/jkBusiness/healthProvider/index'), name: 'jkHealthProvider', meta: { title: '健康厂商接入', icon: '' } },
    { path: 'stockBatch', component: () => import('@/views/jkBusiness/stockBatch/index'), name: 'jkStockBatch', meta: { title: '库存批次与库龄', icon: '' } },
    { path: 'reportAnalysis', component: () => import('@/views/jkBusiness/reportAnalysis/index'), name: 'jkReportAnalysis', meta: { title: '经营分析报表', icon: '' } },
    { path: 'reportExport', component: () => import('@/views/jkBusiness/reportExport/index'), name: 'jkReportExport', meta: { title: '报表导出中心', icon: '' } },
    { path: 'healthDevice', component: () => import('@/views/jkBusiness/healthDevice/index'), name: 'jkHealthDevice', meta: { title: '健康设备管理', icon: '' } },
    { path: 'healthBind', component: () => import('@/views/jkBusiness/healthBind/index'), name: 'jkHealthBind', meta: { title: '设备绑定记录', icon: '' } },
    { path: 'healthData', component: () => import('@/views/jkBusiness/healthData/index'), name: 'jkHealthData', meta: { title: '授权健康数据', icon: '' } },
    { path: 'healthAuthorization', component: () => import('@/views/jkBusiness/healthAuthorization/index'), name: 'jkHealthAuthorization', meta: { title: '健康授权查询', icon: '' } },
    { path: 'healthAlertRule', component: () => import('@/views/jkBusiness/healthAlertRule/index'), name: 'jkHealthAlertRule', meta: { title: '健康预警规则', icon: '' } },
    { path: 'healthAlertRecord', component: () => import('@/views/jkBusiness/healthAlertRecord/index'), name: 'jkHealthAlertRecord', meta: { title: '健康预警处理', icon: '' } },
    { path: 'healthAccessLog', component: () => import('@/views/jkBusiness/healthAccessLog/index'), name: 'jkHealthAccessLog', meta: { title: '健康访问日志', icon: '' } },
    { path: 'healthSync', component: () => import('@/views/jkBusiness/healthSync/index'), name: 'jkHealthSync', meta: { title: '健康同步日志', icon: '' } },
    { path: 'healthIntegration', component: () => import('@/views/jkBusiness/healthIntegration/index'), name: 'jkHealthIntegration', meta: { title: '健康接入状态', icon: '' } },
    { path: 'reportOverview', component: () => import('@/views/jkBusiness/reportOverview/index'), name: 'jkReportOverview', meta: { title: '业务总览报表', icon: '' } },
    { path: 'riskEvent', component: () => import('@/views/jkBusiness/riskEvent/index'), name: 'jkRiskEvent', meta: { title: '风险事件中心', icon: '' } },
    { path: 'riskRule', component: () => import('@/views/jkBusiness/riskRule/index'), name: 'jkRiskRule', meta: { title: '风险规则配置', icon: '' } },
    { path: 'businessEvent', component: () => import('@/views/jkBusiness/businessEvent/index'), name: 'jkBusinessEvent', meta: { title: '业务事件补偿', icon: '' } },
    { path: 'accountReconcile', component: () => import('@/views/jkBusiness/accountReconcile/index'), name: 'jkAccountReconcile', meta: { title: '账户对账', icon: '' } },
    { path: 'relationChange', component: () => import('@/views/jkBusiness/relationChange/index'), name: 'jkRelationChange', meta: { title: '换绑申请审核', icon: '' } },
    { path: 'stockTransferReturn', component: () => import('@/views/jkBusiness/stockTransferReturn/index'), name: 'jkStockTransferReturn', meta: { title: '调拨退回管理', icon: '' } },
    { path: 'region', component: () => import('@/views/jkBusiness/region/index'), name: 'jkRegion', meta: { title: '区域管理', icon: '' } },
    { path: 'regionAgent', component: () => import('@/views/jkBusiness/regionAgent/index'), name: 'jkRegionAgent', meta: { title: '区域代理配置', icon: '' } },
    { path: 'agentRelation', component: () => import('@/views/jkBusiness/agentRelation/index'), name: 'jkAgentRelation', meta: { title: '上下级关系管理', icon: '' } },
    { path: 'adminMapping', component: () => import('@/views/jkBusiness/adminMapping/index'), name: 'jkAdminMapping', meta: { title: '后台账号业务映射', icon: '' } },
    { path: 'dict', component: () => import('@/views/jkBusiness/dict/index'), name: 'jkDict', meta: { title: '业务字典管理', icon: '' } },
    { path: 'commissionFlow', component: () => import('@/views/jkBusiness/commissionFlow/index'), name: 'jkCommissionFlow', meta: { title: '佣金流水', icon: '' } },
    { path: 'commissionRule', component: () => import('@/views/jkBusiness/commissionRule/index'), name: 'jkCommissionRule', meta: { title: '分佣规则管理', icon: '' } },
    { path: 'commissionRecord', component: () => import('@/views/jkBusiness/commissionRecord/index'), name: 'jkCommissionRecord', meta: { title: '佣金明细', icon: '' } },
    { path: 'commissionAccount', component: () => import('@/views/jkBusiness/commissionAccount/index'), name: 'jkCommissionAccount', meta: { title: '佣金账户', icon: '' } },
    { path: 'commissionReverse', component: () => import('@/views/jkBusiness/commissionReverse/index'), name: 'jkCommissionReverse', meta: { title: '佣金冲正记录', icon: '' } },
    { path: 'commissionSettle', component: () => import('@/views/jkBusiness/commissionSettle/index'), name: 'jkCommissionSettle', meta: { title: '结算任务', icon: '' } },
    { path: 'fundAccount', component: () => import('@/views/jkBusiness/fundAccount/index'), name: 'jkFundAccount', meta: { title: '资金账户', icon: '' } },
    { path: 'fundFlow', component: () => import('@/views/jkBusiness/fundFlow/index'), name: 'jkFundFlow', meta: { title: '资金流水', icon: '' } },
    { path: 'withdrawAudit', component: () => import('@/views/jkBusiness/withdrawAudit/index'), name: 'jkWithdrawAudit', meta: { title: '提现审核', icon: '' } },
    {
      path: 'platformOrder',
      component: () => import('@/views/jkBusiness/platformOrder/index'),
      name: 'jkPlatformOrder',
      meta: { title: '区县代订货管理', icon: '' },
    },
    {
      path: 'stockTransfer',
      component: () => import('@/views/jkBusiness/stockTransfer/index'),
      name: 'jkStockTransfer',
      meta: { title: '创客/合伙人调拨管理', icon: '' },
    },
    {
      path: 'businessRole',
      component: () => import('@/views/jkBusiness/businessRole/index'),
      name: 'jkBusinessRole',
      meta: { title: '业务角色管理', icon: '' },
    },
    {
      path: 'businessPermission',
      component: () => import('@/views/jkBusiness/businessPermission/index'),
      name: 'jkBusinessPermission',
      meta: { title: '业务权限点管理', icon: '' },
    },
    {
      path: 'identityApply',
      component: () => import('@/views/jkBusiness/identityApplyAudit/index'),
      name: 'jkIdentityApplyAudit',
      meta: { title: '身份申请审核', icon: '' },
    },
    {
      path: 'userRole',
      component: () => import('@/views/jkBusiness/userBusinessIdentity/index'),
      name: 'jkUserBusinessIdentity',
      meta: { title: '用户业务身份管理', icon: '' },
    },
    {
      path: 'auditLog',
      component: () => import('@/views/jkBusiness/auditLog/index'),
      name: 'jkAuditLog',
      meta: { title: '审核日志', icon: '' },
    },
    {
      path: 'priceRule',
      component: () => import('@/views/jkBusiness/priceRule/index'),
      name: 'jkPriceRule',
      meta: { title: '价格规则管理', icon: '' },
    },
    {
      path: 'stockAccount',
      component: () => import('@/views/jkBusiness/stockAccount/index'),
      name: 'jkStockAccount',
      meta: { title: '库存账户底座', icon: '' },
    },
    {
      path: 'stockItem',
      component: () => import('@/views/jkBusiness/stockItem/index'),
      name: 'jkStockItem',
      meta: { title: '库存明细查询', icon: '' },
    },
    {
      path: 'stockFlow',
      component: () => import('@/views/jkBusiness/stockFlow/index'),
      name: 'jkStockFlow',
      meta: { title: '库存流水查询', icon: '' },
    },
  ],
};

export default jkBusinessRouter;
