<template>
  <div class="app-container">
    <el-alert title="V1 换绑规则：存在未完成调拨、可用/冻结库存、待结算佣金或处理中提现时禁止提交；审核通过只影响后续新业务，历史订单归属不变。" type="info" :closable="false" style="margin-bottom:16px" />
    <div class="filter-container"><el-select v-model="query.userId" clearable filterable remote :remote-method="searchUsers" :loading="userLoading" placeholder="申请人姓名/手机号" class="filter-item" style="width:240px"><el-option v-for="x in userOptions" :key="x.value" :label="x.label" :value="Number(x.value)" /></el-select><el-select v-model="query.status" clearable placeholder="状态" class="filter-item" style="width:140px"><el-option label="待审核" value="PENDING"/><el-option label="已通过" value="APPROVED"/><el-option label="已驳回" value="REJECTED"/><el-option label="已取消" value="CANCELLED"/></el-select><el-button type="primary" @click="load">查询</el-button></div>
    <el-table v-loading="loading" :data="list" border><el-table-column prop="applyNo" label="申请单号" min-width="170"/><el-table-column label="申请人" min-width="170"><template slot-scope="{row}">{{row.userName||'--'}} / {{row.userPhone||row.userId}}</template></el-table-column><el-table-column prop="currentParentName" label="当前上级" min-width="130"/><el-table-column prop="targetParentName" label="目标上级" min-width="130"/><el-table-column prop="applyReason" label="换绑原因" min-width="180"/><el-table-column label="状态" width="100"><template slot-scope="{row}">{{row.statusText||row.status}}</template></el-table-column><el-table-column prop="rejectReason" label="驳回原因" min-width="160"/><el-table-column prop="createTime" label="申请时间" min-width="160"/><el-table-column label="操作" width="130" fixed="right"><template slot-scope="{row}"><template v-if="row.status==='PENDING'"><el-button type="text" @click="audit(row,true)">通过</el-button><el-button type="text" style="color:#f56c6c" @click="audit(row,false)">驳回</el-button></template></template></el-table-column></el-table>
  </div>
</template>
<script>
import { getJkRelationChangeList, auditJkRelationChange, getJkUserOptions } from '@/api/jkBusiness'
export default {data(){return{query:{},list:[],loading:false,userOptions:[],userLoading:false}},created(){this.searchUsers('');this.load()},methods:{searchUsers(keyword){this.userLoading=true;getJkUserOptions({keyword,limit:30}).then(r=>{this.userOptions=(r&&r.data)||r||[]}).finally(()=>this.userLoading=false)},load(){this.loading=true;getJkRelationChangeList(this.query).then(r=>{this.list=(r&&r.list)||(r&&r.data&&r.data.list)||r.data||r||[]}).finally(()=>this.loading=false)},audit(row,pass){this.$prompt(pass?'请输入审核备注':'请输入驳回原因',pass?'通过换绑':'驳回换绑',{inputPattern:/\S+/,inputErrorMessage:'不能为空'}).then(({value})=>auditJkRelationChange({applyId:row.id,approved:pass,remark:value,requestNo:'REL-AUDIT-'+Date.now()}).then(()=>{this.$message.success('处理完成');this.load()}))}}}
</script>
