<template>
  <div class="divBox">
    <el-alert title="补发、退款、退回和接受现状必须按异常商品逐项分配，处理数量不得超过少货与破损剩余数量。涉及资金或退货时不会只改状态为已解决。" type="warning" :closable="false" />
    <el-card shadow="never" class="mt14">
      <el-form :inline="true" size="mini"><el-form-item label="异常单ID"><el-input-number v-model="exceptionId" :min="1" controls-position="right" /></el-form-item><el-form-item><el-button type="primary" @click="load">查询处理方案</el-button><el-button type="success" :disabled="!exceptionId" @click="openCreate">创建处理方案</el-button></el-form-item></el-form>
      <el-empty v-if="loaded&&!list.length" description="该异常单暂无V2处理方案" />
      <el-card v-for="x in list" :key="x.id" shadow="never" class="resolution">
        <div slot="header" class="head"><div><strong>{{x.resolutionNo}}</strong><el-tag size="mini" class="ml8">{{x.resolutionTypeText||typeText(x.resolutionType)}}</el-tag></div><el-tag size="mini" :type="x.resolutionStatus==='COMPLETED'?'success':x.resolutionStatus==='CANCELLED'?'info':'warning'">{{x.resolutionStatusText||statusText(x.resolutionStatus)}}</el-tag></div>
        <el-descriptions :column="4" size="mini"><el-descriptions-item label="接受数量">{{x.acceptedQuantity||0}}</el-descriptions-item><el-descriptions-item label="补发数量">{{x.reshipQuantity||0}}</el-descriptions-item><el-descriptions-item label="退款金额">¥{{money(x.refundAmount)}}</el-descriptions-item><el-descriptions-item label="索赔金额">¥{{money(x.claimAmount)}}</el-descriptions-item></el-descriptions>
        <el-table :data="x.items||[]" size="mini"><el-table-column prop="productId" label="商品ID" width="90"/><el-table-column prop="skuId" label="SKU" width="90"/><el-table-column prop="acceptedQty" label="接受" width="70"/><el-table-column prop="reshipQty" label="补发" width="70"/><el-table-column prop="refundQty" label="退款" width="70"/><el-table-column prop="returnQty" label="退回" width="70"/><el-table-column label="补发物流" min-width="180"><template slot-scope="{row}">{{row.logisticsCompany||'--'}} / {{row.logisticsNo||'--'}}</template></el-table-column><el-table-column prop="itemRemark" label="说明" min-width="160"/></el-table>
        <div v-if="x.resolutionStatus==='PENDING_CONFIRM'" class="actions"><el-button size="mini" type="primary" @click="complete(x)">确认真实完成</el-button><el-button size="mini" @click="cancel(x)">取消方案</el-button></div>
      </el-card>
    </el-card>

    <el-dialog title="创建异常收货V2处理方案" :visible.sync="visible" width="850px">
      <el-form label-width="100px"><el-form-item label="处理类型"><el-select v-model="form.resolutionType" @change="resetQuantities"><el-option label="补发" value="RESHIP"/><el-option label="差额退款" value="REFUND"/><el-option label="退回异常商品" value="RETURN"/><el-option label="接受现状" value="ACCEPT"/><el-option label="组合处理" value="MIXED"/></el-select></el-form-item><el-form-item label="责任方"><el-select v-model="form.responsibilityParty" clearable><el-option label="平台" value="PLATFORM"/><el-option label="发货方" value="SENDER"/><el-option label="物流" value="LOGISTICS"/><el-option label="收货方" value="RECEIVER"/></el-select></el-form-item><el-form-item v-if="hasRefund" label="退款金额"><el-input-number v-model="form.refundAmount" :min="0" :precision="2" /></el-form-item><el-form-item label="处理说明"><el-input v-model="form.remark" type="textarea" /></el-form-item></el-form>
      <el-table :data="form.items" size="mini"><el-table-column prop="exceptionItemId" label="异常明细ID" width="110"/><el-table-column label="接受" width="110"><template slot-scope="{row}"><el-input-number v-model="row.acceptedQty" :min="0" size="mini" controls-position="right"/></template></el-table-column><el-table-column label="补发" width="110"><template slot-scope="{row}"><el-input-number v-model="row.reshipQty" :min="0" size="mini" controls-position="right"/></template></el-table-column><el-table-column label="退款" width="110"><template slot-scope="{row}"><el-input-number v-model="row.refundQty" :min="0" size="mini" controls-position="right"/></template></el-table-column><el-table-column label="退回" width="110"><template slot-scope="{row}"><el-input-number v-model="row.returnQty" :min="0" size="mini" controls-position="right"/></template></el-table-column><el-table-column label="物流公司" min-width="120"><template slot-scope="{row}"><el-input v-model="row.logisticsCompany" size="mini"/></template></el-table-column><el-table-column label="物流单号" min-width="130"><template slot-scope="{row}"><el-input v-model="row.logisticsNo" size="mini"/></template></el-table-column></el-table>
      <div class="add-row"><el-input-number v-model="newItemId" :min="1" controls-position="right"/><el-button @click="addItem">添加异常商品明细</el-button></div>
      <span slot="footer"><el-button @click="visible=false">取消</el-button><el-button type="primary" :loading="saving" @click="save">保存待确认方案</el-button></span>
    </el-dialog>
  </div>
</template>
<script>
import { getReceiveResolutionList, createReceiveResolution, completeReceiveResolution, cancelReceiveResolution } from '@/api/jkPhase3'
export default{data(){return{exceptionId:Number(this.$route.query.exceptionId)||null,loaded:false,list:[],visible:false,saving:false,newItemId:null,form:{resolutionType:'RESHIP',responsibilityParty:'',refundAmount:0,claimAmount:0,remark:'',items:[]}}},computed:{hasRefund(){return this.form.resolutionType==='REFUND'||this.form.resolutionType==='MIXED'}},created(){if(this.exceptionId)this.load()},methods:{load(){if(!this.exceptionId)return this.$message.warning('请输入异常单ID');this.loaded=false;getReceiveResolutionList({exceptionId:this.exceptionId}).then(r=>{this.list=r.data||r||[]}).finally(()=>this.loaded=true)},openCreate(){this.form={resolutionType:'RESHIP',responsibilityParty:'',refundAmount:0,claimAmount:0,remark:'',items:[]};this.visible=true},addItem(){if(!this.newItemId)return;if(this.form.items.some(x=>x.exceptionItemId===this.newItemId))return this.$message.warning('该明细已添加');this.form.items.push({exceptionItemId:this.newItemId,acceptedQty:0,reshipQty:0,refundQty:0,returnQty:0,logisticsCompany:'',logisticsNo:'',itemRemark:''});this.newItemId=null},resetQuantities(){this.form.items.forEach(x=>{x.acceptedQty=0;x.reshipQty=0;x.refundQty=0;x.returnQty=0})},save(){if(!this.form.items.length||!this.form.remark)return this.$message.warning('请填写处理明细和说明');this.saving=true;createReceiveResolution({...this.form,exceptionId:this.exceptionId,requestNo:'RESOLUTION-'+this.exceptionId+'-'+Date.now(),evidenceUrls:[]}).then(()=>{this.$message.success('处理方案已创建，尚未执行库存或资金动作');this.visible=false;this.load()}).finally(()=>this.saving=false)},complete(x){this.$prompt('请确认补发/退款/退回等真实动作已经完成，并填写依据','确认处理完成',{inputValidator:v=>!!String(v||'').trim()||'说明不能为空'}).then(({value})=>completeReceiveResolution({resolutionId:x.id,requestNo:'COMPLETE-'+x.id+'-'+Date.now(),remark:value}).then(()=>{this.$message.success('处理进度已更新');this.load()})).catch(()=>{})},cancel(x){this.$prompt('请输入取消原因','取消处理方案',{inputValidator:v=>!!String(v||'').trim()||'原因不能为空'}).then(({value})=>cancelReceiveResolution({resolutionId:x.id,requestNo:'CANCEL-'+x.id+'-'+Date.now(),remark:value}).then(()=>{this.$message.success('方案已取消');this.load()})).catch(()=>{})},money(v){return Number(v||0).toFixed(2)},typeText(v){return {RESHIP:'补发',REFUND:'差额退款',RETURN:'退回异常商品',ACCEPT:'接受现状',MIXED:'组合处理'}[v]||v},statusText(v){return {PENDING_CONFIRM:'待确认',COMPLETED:'已完成',CANCELLED:'已取消'}[v]||v}}}
</script>
<style scoped>.mt14{margin-top:14px}.resolution{margin-top:14px}.head{display:flex;align-items:center;justify-content:space-between}.ml8{margin-left:8px}.actions{margin-top:14px;text-align:right}.add-row{display:flex;gap:10px;margin-top:12px}</style>
