<template>
  <div class="app-container">
    <div class="filter-container"><el-select v-model="query.sourceType" clearable placeholder="来源类型" class="filter-item"><el-option label="零售订单" value="RETAIL_ORDER" /></el-select><el-select v-model="query.receiverRoleCode" clearable placeholder="收益身份" class="filter-item"><el-option v-for="item in roleOptions" :key="item.roleCode" :label="item.roleName" :value="item.roleCode" /></el-select><el-select v-model="query.status" clearable placeholder="规则状态" class="filter-item"><el-option label="启用" :value="true" /><el-option label="禁用" :value="false" /></el-select><el-button type="primary" @click="load">查询</el-button><el-button type="success" @click="openRule()">新增规则</el-button></div>
    <el-table v-loading="loading" :data="list" border><el-table-column prop="ruleNo" label="规则编号" min-width="150" /><el-table-column prop="ruleName" label="规则名称" min-width="150" /><el-table-column label="来源" min-width="120"><template slot-scope="{row}">{{ row.sourceTypeText || row.sourceType || '--' }}</template></el-table-column><el-table-column label="收益身份" min-width="120"><template slot-scope="{row}">{{ row.receiverRoleName || '身份未配置' }}</template></el-table-column><el-table-column prop="ruleVersion" label="版本" /><el-table-column prop="freezeDays" label="冻结天数" /><el-table-column prop="status" label="状态"><template slot-scope="{row}">{{ row.statusText || (row.status ? '启用' : '禁用') }}</template></el-table-column><el-table-column label="操作" width="260"><template slot-scope="{row}"><el-button size="mini" @click="openRule(row)">编辑</el-button><el-button size="mini" @click="openItems(row)">规则明细</el-button><el-button size="mini" :type="row.status ? 'warning' : 'success'" @click="toggleRule(row)">{{ row.status ? '禁用' : '启用' }}</el-button></template></el-table-column></el-table>
    <el-dialog :title="ruleForm.id ? '编辑规则' : '新增规则'" :visible.sync="ruleVisible" width="620px"><el-form :model="ruleForm" label-width="100px"><el-form-item label="规则名称"><el-input v-model="ruleForm.ruleName" /></el-form-item><el-form-item label="来源类型"><el-select v-model="ruleForm.sourceType"><el-option label="零售订单" value="RETAIL_ORDER" /></el-select></el-form-item><el-form-item label="收益身份"><el-select v-model="ruleForm.receiverRoleCode"><el-option v-for="item in roleOptions" :key="item.roleCode" :label="item.roleName" :value="item.roleCode" /></el-select></el-form-item><el-form-item label="规则版本"><el-input-number v-model="ruleForm.ruleVersion" :min="1" /></el-form-item><el-form-item label="冻结天数"><el-input-number v-model="ruleForm.freezeDays" :min="0" /><span class="hint">由业务配置，不预置默认值</span></el-form-item><el-form-item label="兜底规则"><el-input v-model="ruleForm.ruleConfigJson" type="textarea" :rows="4" placeholder="未命中规则明细时使用，例如：{&quot;calculationType&quot;:&quot;PERCENT&quot;,&quot;commissionRate&quot;:0.05}" /></el-form-item><el-form-item label="备注"><el-input v-model="ruleForm.remark" /></el-form-item></el-form><div slot="footer"><el-button @click="ruleVisible=false">取消</el-button><el-button type="primary" @click="saveRule">保存</el-button></div></el-dialog>
    <el-dialog :title="itemRule ? itemRule.ruleName + '：规则明细' : '规则明细'" :visible.sync="itemVisible" width="900px"><el-button type="success" size="mini" @click="openItem()">新增明细</el-button><el-table v-loading="itemLoading" :data="items" border style="margin-top:12px"><el-table-column label="收益身份" min-width="120"><template slot-scope="{row}">{{ row.receiverRoleName || '继承主规则' }}</template></el-table-column><el-table-column label="计算方式" min-width="110"><template slot-scope="{row}">{{ row.calculationTypeText || row.calculationType || '--' }}</template></el-table-column><el-table-column prop="commissionRate" label="比例" /><el-table-column prop="fixedAmount" label="固定金额" /><el-table-column prop="priority" label="优先级" /><el-table-column prop="status" label="状态"><template slot-scope="{row}">{{ row.statusText || (row.status ? '启用' : '禁用') }}</template></el-table-column><el-table-column label="操作" width="180"><template slot-scope="{row}"><el-button size="mini" @click="openItem(row)">编辑</el-button><el-button size="mini" @click="toggleItem(row)">{{ row.status ? '禁用' : '启用' }}</el-button></template></el-table-column></el-table><el-dialog title="规则明细" :visible.sync="itemFormVisible" append-to-body width="560px"><el-form :model="itemForm" label-width="100px"><el-form-item label="收益身份"><el-select v-model="itemForm.receiverRoleCode" clearable placeholder="留空则继承主规则"><el-option v-for="item in roleOptions" :key="item.roleCode" :label="item.roleName" :value="item.roleCode" /></el-select></el-form-item><el-form-item label="计算方式"><el-select v-model="itemForm.calculationType"><el-option label="比例" value="PERCENT" /><el-option label="固定金额" value="FIXED" /></el-select></el-form-item><el-form-item v-if="itemForm.calculationType === 'PERCENT'" label="佣金比例"><el-input-number v-model="itemForm.commissionRate" :min="0" :max="1" :step="0.001" /></el-form-item><el-form-item v-else label="固定金额"><el-input-number v-model="itemForm.fixedAmount" :min="0" :precision="2" /></el-form-item><el-form-item label="优先级"><el-input-number v-model="itemForm.priority" :min="0" /></el-form-item></el-form><div slot="footer"><el-button @click="itemFormVisible=false">取消</el-button><el-button type="primary" @click="saveItem">保存</el-button></div></el-dialog></el-dialog>
  </div>
</template>
<script>
import { getJkBusinessRoleList, getJkCommissionRuleItemList, getJkCommissionRuleList, saveJkCommissionRule, saveJkCommissionRuleItem, updateJkCommissionRuleItemStatus, updateJkCommissionRuleStatus } from '@/api/jkBusiness'
const emptyRule = () => ({ id: null, ruleName: '', ruleVersion: 1, sourceType: 'RETAIL_ORDER', receiverRoleCode: '', freezeDays: null, ruleConfigJson: '', remark: '' })
const emptyItem = ruleId => ({ id: null, ruleId, receiverRoleCode: '', calculationType: 'PERCENT', commissionRate: null, fixedAmount: null, priority: 0 })
export default { data() { return { list: [], loading: false, roleOptions: [], query: { sourceType: '', receiverRoleCode: '', status: null }, ruleVisible: false, ruleForm: emptyRule(), itemVisible: false, itemFormVisible: false, itemRule: null, items: [], itemLoading: false, itemForm: emptyItem(null) } }, created() { this.loadRoles(); this.load() }, methods: { loadRoles() { getJkBusinessRoleList({ page: 1, limit: 100, enabled: true }).then(response => { this.roleOptions = response.data || response || [] }) }, load() { this.loading = true; getJkCommissionRuleList(this.query).then(response => { this.list = response.data || response || [] }).finally(() => { this.loading = false }) }, openRule(row) { this.ruleForm = row ? Object.assign({}, row) : emptyRule(); this.ruleVisible = true }, saveRule() { saveJkCommissionRule(this.ruleForm).then(() => { this.$message.success('保存成功'); this.ruleVisible = false; this.load() }) }, toggleRule(row) { updateJkCommissionRuleStatus(row.id, !row.status).then(() => { this.$message.success('状态已更新'); this.load() }) }, openItems(rule) { this.itemRule = rule; this.itemVisible = true; this.loadItems() }, loadItems() { this.itemLoading = true; getJkCommissionRuleItemList({ ruleId: this.itemRule.id }).then(response => { this.items = response.data || response || [] }).finally(() => { this.itemLoading = false }) }, openItem(row) { this.itemForm = row ? Object.assign({}, row) : emptyItem(this.itemRule.id); this.itemFormVisible = true }, saveItem() { saveJkCommissionRuleItem(this.itemForm).then(() => { this.$message.success('规则明细已保存'); this.itemFormVisible = false; this.loadItems() }) }, toggleItem(row) { updateJkCommissionRuleItemStatus(row.id, !row.status).then(() => { this.$message.success('状态已更新'); this.loadItems() }) } }}
</script>
<style scoped>.filter-item{width:150px;margin-right:8px}.hint{margin-left:8px;color:#999;font-size:12px}</style>
